export {
  attachVehicleFile,
  availableVehicles,
  createVehicle,
  daysUntilLicensing,
  daysWithoutRental,
  DEFAULT_VEHICLE_SORT,
  DERIVED_VEHICLE_STATUSES,
  findVehicle,
  fleetFilterOptions,
  fleetStatusCounts,
  fleetSummary,
  licensingAlert,
  LICENSING_WARNING_DAYS,
  listVehicles,
  LONG_STOP_DAYS,
  MANAGER_VEHICLE_STATUSES,
  kmUntilRevision,
  removeVehicle,
  removeVehicles,
  revisionAlert,
  revisionDefault,
  REVISION_WARNING_KM,
  setRevisionDefault,
  setVehicleStatus,
  setVehiclesStatus,
  signedFileUrl,
  updateVehicle,
  vehiclePlates,
  VEHICLE_FILE_KINDS,
  VEHICLE_SORTS,
  VEHICLE_STATUSES,
  VEHICLES_PER_PAGE,
  type AvailableVehicle,
  type FleetFilterOptions,
  type FleetStatusCounts,
  type FleetSummary,
  type LicensingAlert,
  type RevisionAlert,
  type NewVehicle,
  type SignedUrlOptions,
  type DerivedVehicleStatus,
  type SortDirection,
  type Vehicle,
  type VehicleFileKind,
  type VehicleFilters,
  type VehicleSort,
  type VehicleStatus,
} from "./vehicles";
